 name : Postman Collection Workflow
 
 on: 
   push:
     branches: [main]
   workflow_dispatch:
   schedule:
     - cron : 30 02 * * * #8 am IST Every Day
     - cron : 00 14 * * * # 7:30 pm IST Every Day
     - cron : 00 06 * * 1-5 # 11:30 an IST Monday to Friday

 jobs:
   run-postman-test:
     runs-on: ubunto-latest

     steps:
      - name: checkout the code
        uses: actions/checkout@v4.2.2

      - name: Install nodejs and npm
        uses: actions/setup-node@v3.9.1
        with: 
          node-version: '22'

      - name: Install Newman and Html-extra globally
        run: | 
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run the postman Collection with newman
        run: |
            newman run 'Inwarranty-flow Collection.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testData.csv \
            -r cli,htmlextra            
      - name: Newman Report
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: Newman Report
          path: newman/*.html
          
          
      
     
  
       
  
